on:
  workflow_dispatch:
jobs:
  init:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    permissions:
      contents: write
    steps:
      - name: checkout trunk
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install prerequisites
        run: |
          apt-get update
          apt-get install --allow-downgrades -y git git-svn subversion
      - name: configure svn credential storage
        run: |
          mkdir -p ~/.subversion
          cat > ~/.subversion/servers <<EOF
          [global]
          store-passwords = yes
          store-auth-creds = yes
          EOF
      - name: configure git identity
        run: |
          git config --global user.name "eoschdk-aggregate[bot]"
          git config --global user.email "eoschdk-aggregate[bot]@users.noreply.github.com"
      - name: clone svn repository
        env:
          SVN_USERNAME: guest
          SVN_PASSWORD: guest
        run: |
          echo "$SVN_PASSWORD" | \
          git svn clone -s https://subversion.assembla.com/svn/chdk \
            --username "$SVN_USERNAME" \
            svn-mirror
      - name: restore workflow files to trunk
        run: |
          mkdir -p svn-mirror/.github/workflows/
          cp .github/workflows/svn-clone.yml svn-mirror/.github/workflows/svn-clone.yml
          cp .github/workflows/svn-fetch.yml svn-mirror/.github/workflows/svn-fetch.yml

          cd svn-mirror
          git add .github/workflows/svn-clone.yml .github/workflows/svn-fetch.yml
          git commit -m $'restore workflow
          
          Co-authored-by: Mahied Maruf <contact@mechite.com>
          Co-authored-by: Enzo van der Tuin <55853439+JegoxMC@users.noreply.github.com>
          Signed-off-by: eoschdk-aggregate <eoschdk-aggregate[bot]@users.noreply.github.com>'
      - name: push canonical mirror to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd svn-mirror
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
          git push origin --all --force
          git push origin --tags --force
